language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "lts/*"
  - "7"
  - "8"

script:
  - npm install
  - npm run lint

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  repo: luanvuvt/luanvuvt.github.io
  on:
    branch: master